### ISSUE TITLE
Making buildcal & extractcube callable from Python

### ISSUE THREAD

**Issue by tltobin** [PrincetonUniversity/charis-dep#20]
Hi, I was wondering if the following modifications could be made to the main buildcal/extractcube scripts for the automated CHARIS data processing backend I've been working on. They're relatively minor, and I'm happy to help or provide more information, if needed:

1. Currently, the top-level extractcube and buildcal functions are callable only from the command line. While they both reference the python function in the same script, there is still a not-insignificant amount of processing that only occurs when called from the command line. 

For consistency with any future updates, would it be possible to slightly restructure these two main scripts:

    a. Have a top-level "main" python function for each extractcube and buildcal that serves as the wrapper for the function. The main python function for buildcal would ideally not include any prompts for user input, assuming all have been provided on call. The main python function for extractcube would include reading in the init file.> 

    b. Adjust the section that allows it to be callable from the command line to only (i) prompt any required user input, and (ii) hand the user-provided parameters to the main Python function.

2. Allow output from extractcube and buildcal to be ported to a specified subdirectory other than the current working directory. This path can be provided to the main python functions from (1a).

**Comment by m-samland** [comment]
Version 2 of the pipeline incorporates callable functions for buildcal and extractcube and specification of output directories.
